 function buildFounderFrameReport(run) {
  const { data, score, gate, sprint } = run;
  const createdAt = new Date().toISOString();

  const metrics = Object.entries(score.metrics)
    .map(([key, value]) => `- ${key.toUpperCase()}: ${value}`)
    .join("\n");

  const issues = gate.issues.length
    ? gate.issues.map(issue => `- ${issue}`).join("\n")
    : "- No critical blockers detected. Continue with human review.";

  const sprintItems = sprint
    .map(item => `- ${item.day}: ${item.task}\n  Proof: ${item.proof}`)
    .join("\n");

  return `# Founder Frame OS Report

Generated: ${createdAt}

## CLEARANCE Status

${gate.status}

## Total Score

${score.total}/100

## Metric Scores

${metrics}

## Quality Gate Issues

${issues}

## Founder Intake

### Vision
${data.vision}

### Problem
${data.problem}

### Target User
${data.user}

### Solution
${data.solution}

### Proof
${data.proof || "No proof provided."}

### Revenue Path
${data.revenue || "No revenue path provided."}

### Execution Commitment
${data.execution}

## 7-Day Execution Sprint

${sprintItems}

## Governance Boundary

This report is generated by an internal prototype.

It does not authorize public release, monetization, controlled user testing, institutional use, customer-facing deployment, or external claims.

CLEARANCE posture: PROCEED INTERNAL / PAUSE EXTERNAL
`;
}

function downloadFounderFrameReport() {
  const savedRun = localStorage.getItem("founderFrameLastRun");

  if (!savedRun) {
    alert("No Founder Frame result is available yet. Run the intake first.");
    return;
  }

  const run = JSON.parse(savedRun);
  const report = buildFounderFrameReport(run);
  const blob = new Blob([report], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = "founder-frame-report.md";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

function addDownloadReportButton() {
  const dashboard = document.getElementById("dashboard");

  if (!dashboard || dashboard.classList.contains("hidden")) {
    return;
  }

  if (document.getElementById("download-report")) {
    return;
  }

  const button = document.createElement("button");
  button.id = "download-report";
  button.type = "button";
  button.textContent = "Download Founder Frame Report";
  button.addEventListener("click", downloadFounderFrameReport);

  dashboard.appendChild(button);
}

document.getElementById("intake-form").addEventListener("submit", function () {
  setTimeout(addDownloadReportButton, 0);
});