const REPORT_VERSION = "FFOS_REPORT_EXPORT_v0.4";
const CLEARANCE_POSTURE = "PROCEED INTERNAL / PAUSE EXTERNAL";

function padTimePart(value) {
  return String(value).padStart(2, "0");
}

function createReportTimestamp(date) {
  const year = date.getUTCFullYear();
  const month = padTimePart(date.getUTCMonth() + 1);
  const day = padTimePart(date.getUTCDate());
  const hour = padTimePart(date.getUTCHours());
  const minute = padTimePart(date.getUTCMinutes());
  const second = padTimePart(date.getUTCSeconds());

  return `${year}${month}${day}T${hour}${minute}${second}Z`;
}

function createReportId(date) {
  return `FFOS-RPT-${createReportTimestamp(date)}`;
}

function createReportFilename(date) {
  const timestamp = createReportTimestamp(date).toLowerCase();
  return `founder-frame-report-${timestamp}.md`;
}

function buildFounderFrameReport(run, metadata) {
  const { data, score, gate, sprint } = run;
  const reportId = metadata.reportId;
  const reportVersion = metadata.reportVersion;
  const generatedAt = metadata.generatedAt;
  const clearancePosture = metadata.clearancePosture;

  const metrics = Object.entries(score.metrics)
    .map(([key, value]) => `- ${key.toUpperCase()}: ${value}`)
    .join("\n");

  const issues = gate.issues.length
    ? gate.issues.map(issue => `- ${issue}`).join("\n")
    : "- No critical blockers detected. Continue with human review.";

  const sprintItems = sprint
    .map(item => `- ${item.day}: ${item.task}\n  Proof: ${item.proof}`)
    .join("\n");

  return `# Founder Frame OS Report

## Report Control

Report ID: ${reportId}

Report Version: ${reportVersion}

Generated: ${generatedAt}

CLEARANCE Posture: ${clearancePosture}

## CLEARANCE Status

${gate.status}

## Total Score

${score.total}/100

## Metric Scores

${metrics}

## Quality Gate Issues

${issues}

## Founder Intake

### Vision
${data.vision}

### Problem
${data.problem}

### Target User
${data.user}

### Solution
${data.solution}

### Proof
${data.proof || "No proof provided."}

### Revenue Path
${data.revenue || "No revenue path provided."}

### Execution Commitment
${data.execution}

## 7-Day Execution Sprint

${sprintItems}

## Governance Boundary

This report is generated by an internal prototype.

It does not authorize public release, monetization, controlled user testing, institutional use, customer-facing deployment, or external claims.

CLEARANCE posture: ${clearancePosture}
`;
}

function downloadFounderFrameReport() {
  const savedRun = localStorage.getItem("founderFrameLastRun");

  if (!savedRun) {
    alert("No Founder Frame result is available yet. Run the intake first.");
    return;
  }

  let run;

  try {
    run = JSON.parse(savedRun);
  } catch (error) {
    alert("Saved Founder Frame result could not be read. Run the intake again.");
    return;
  }

  const generatedAtDate = new Date();

  const metadata = {
    reportId: createReportId(generatedAtDate),
    reportVersion: REPORT_VERSION,
    generatedAt: generatedAtDate.toISOString(),
    clearancePosture: CLEARANCE_POSTURE
  };

  const report = buildFounderFrameReport(run, metadata);
  const blob = new Blob([report], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = createReportFilename(generatedAtDate);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

function addDownloadReportButton() {
  const dashboard = document.getElementById("dashboard");

  if (!dashboard || dashboard.classList.contains("hidden")) {
    return;
  }

  if (document.getElementById("download-report")) {
    return;
  }

  const button = document.createElement("button");
  button.id = "download-report";
  button.type = "button";
  button.textContent = "Download Founder Frame Report";
  button.addEventListener("click", downloadFounderFrameReport);

  dashboard.appendChild(button);
}

document.getElementById("intake-form").addEventListener("submit", function () {
  setTimeout(addDownloadReportButton, 0);
});